baseURL: "/"
DefaultContentLanguage: "bn"
defaultContentLanguageInSubdir: "false"
enableMissingTranslationPlaceholders: "false"
timeZone: "Asia/Dhaka"
# enableGitInfo: true
# googleAnalytics: "G-3NFDT41J8E"

paginate: 6

languages:
  bn:
    disabled: false
    # contentDir: content/bn/
    languageCode: bn-BD
    languageDirection: ltr
    languageName: বাংলা
    title: বাংলা উইকিসংযোগ
    weight: 1
    params:
      subtitle: "উইকিমিডিয়ানদের যৌথ উদ্যোগ"
      author:
        name: ঐশিক রেহমান
        jobtitle: উইকিমিডিয়ান ও অভিধানকার (বিসিএসই)
      description: বাংলা উইকিসংযোগ একটি সহযোগিতামূলক উদ্যোগ যা বাংলা ভাষায় উইকিপিডিয়ার বিষয়বস্তু বৃদ্ধি এবং সম্প্রসারণের উপর দৃষ্টি নিবদ্ধ করে।
      cse: 458e08bf4d1094c8e
  en:
    disabled: false
    # contentDir: content/en/
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    title: Bangla WikiConnect
    weight: 2
    params:
      subtitle: "A joint effort of Wikimedians"
      author:
        name: Aishik Rehman
        jobtitle: Wikimedian and Lexicolgist (BCSE)
      description: a Bengali computational linguist and developer with a background in computer science and engineering.
      cse: 02da3ac110b6e40d1

Params:
  defaultColorMode: "light" #Changing this require some changes to colormode.js script, Otherwise it won't work
  activateColorModeToogler: true #To activate color mode dark/light toogler
  activatejQuery: false #In case we need jQuery
  activateGlobalMenu: false #If we want to use Global Menu in case
  useBootstrapMod: true #Mod of Bootsrap 5.3.3, If we don't want to use the mod, we need to set the BootstrapCDNVersion
  useBootstrapIcons: true #To use Botstrap Icons. Recommended is "true"
  userBootstrapBundleJS: true #Bootstarp Bundle Js
  BootstrapCDNVersion: "5.3.3" #Doesnt work if useBootstrapMod is "true", To apply this, we must set useBootstrapMod to false
  defaultLang: bn #Set it the value of same as DefaultContentLanguage, use to check
  google_site_verification: "0J8IfuFx-q_dRuc9I1q0tcVBKAMOTAN3gr27m5OwKzQ"
  fb_app_id: "" #Facebook Application ID
  meta:
    name: Bangla WikiConnect
    alternateName: "WikiConnect"
  author:
    name: Aishik Rehman
    jobtitle: Wikimedian and Lexicolgist and CSEr.
    url: "https://aishikrehman.com/about/"
    email: contact@aishikrehman.com
    locality: Bangladesh
  social:
    facebook: "https://facebook.com/banglawikiconnect"
    linkedin: "https://linkedin.com/in/banglawikiconnect"
    # youtube: "https://youtube.com/@banglawikiconnect"
    github: "https://github.com/bnwp"
    wikipedia: "https://meta.wikimedia.org/wiki/Bangla_WikiConnect"
    #twitter: banglawikiconnect
  phone: "+880 1601660666"
  picture: /assets/images/Aishik Rehman_Mymensingh_2019.jpg
  github:
    user: bnwp
    repo: bnwp.github.io
    branch: main
  og:
    image: /assets/images/Aishik Rehman-og-image.png

taxonomies:
  tag: tags
  team: teams
  

markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
outputs:
  home: ["HTML", "RSS", "JSON"]
